---
abstract: 'Provides interface to SlimTimer web service.'
author:
  - 'Vadim Zeitlin <vz-cpan@zeitlins.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-SlimTimer
no_index:
  file:
    - lib/WebService/SlimTimer/Types.pm
requires:
  DateTime: 0
  DateTime::Format::Natural: 0
  DateTime::Format::RFC3339: 0
  File::Slurp: 0
  File::Spec: 0
  Getopt::Long::Descriptive: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Declare: 0
  MooseX::Method::Signatures: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  YAML::XS: 0
  debug: 0
version: 0.003
